### ISSUE TITLE
Add migration and API change doc for 0.x -> 1.0

### ISSUE THREAD

**Issue by Anthropic** [json-schema-form/angular-schema-form#894]
Add documentation for the following issues found during migration processes carried out by users.

- [x] #901 contribution docs
- [x] #891 schemaForm.merge no longer requires all parameters
- [x] #869 Add Object.assign polyfill or backwards compatibility library for IE support
- [x] #889 x-schema-form should accept all formats for titleMaps
- [x] #890 sfValidator API change
- [x] #896 Change to field names

**Comment by Anthropic** [comment]
All items are covered now, I'll re-open this issue if any more documentation needs pop-up
